# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# apt-get install arduino-mk

#ARDUINO_DIR=/opt/arduino

BOARD_TAG    = pro5v328

include /usr/share/arduino/Arduino.mk

serial:
	microcom -p ${DEVICE_PATH}
